services:

  postgres:
    image: postgres:16
    container_name: order-postgres

    environment:
      POSTGRES_DB: order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: order

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - order-network

  orderaccumulator: 
    build:
      context: .
      dockerfile: OrderAccumulator/OrderAccumulator.Api/dockerfile


    container_name: order-accumulator

    environment:
      ASPNETCORE_ENVIRONMENT: Docker

      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=order;Username=postgres;Password=order

    ports:
      - "5001:8080"

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - order-network

  ordergenerator:
    build:
      context: .
      dockerfile: OrderGenerator/OrderGenerator.Api/dockerfile

    container_name: order-generator

    environment:
      ASPNETCORE_ENVIRONMENT: Docker

      Fix__Host: orderaccumulator
      Fix__Port: 5002

      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=order;Username=postgres;Password=order

    ports:
      - "5000:8080"

    depends_on:
      postgres:
        condition: service_healthy

      orderaccumulator:
        condition: service_started

    networks:
      - order-network
  frontend:
    build:
      context: ./OrderGenerator/Frontend
      args:
        VITE_API_URL: http://localhost:5000
      dockerfile: Dockerfile

    container_name: order-frontend

    ports:
      - "3000:80"

    depends_on:
      - ordergenerator

    networks:
      - order-network

networks:
  order-network:
    driver: bridge

volumes:
  postgres_data: